#Host IP#
Host: 'localhost'
#Query/Server Port#
#Will detect which virtual server your using via the port#
ServerPort: 9987
QueryPort: 10011
#Query Username/Password#
ServerAdminUsername: 'serveradmin'
ServerAdminPassword: 'password'
#Display Names#
#DisplayName for TS in Minecraft#
TSDisplayName: 'MC'
#DisplayName for MC in Teamspeak#
MCDisplayName: 'TS'
#Message format#
#Format for Teamspeak#
TSMessageFormat: '[%DisplayName%]<%PlayerName%>:%Message%'
#Format for Minecraft/Colors work#
MCMessageFormat: '[%DisplayName%]<%PlayerName%>:%Message%'